apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul
  labels:
    app: consul
spec:
  serviceName: "consul"
  replicas: 3
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: hashicorp/consul:latest
        ports:
        - containerPort: 8300
          name: server
        - containerPort: 8301
          name: serflan
        - containerPort: 8302
          name: serfwan
        - containerPort: 8500
          name: http
        - containerPort: 8600
          name: dns
        volumeMounts:
        - name: consul-data
          mountPath: /consul/data
        args:
        - "agent"
        - "-server"
        - "-bootstrap-expect=3"
        - "-ui"
        - "-client=0.0.0.0"
        - "-advertise=$(POD_IP)"
        - "-retry-join=consul-0.consul"
        - "-retry-join=consul-1.consul"
        - "-retry-join=consul-2.consul"
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
  volumeClaimTemplates:
  - metadata:
      name: consul-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: consul
  labels:
    app: consul
spec:
  ports:
  - port: 8300
    name: server
  - port: 8301
    name: serflan
  - port: 8302
    name: serfwan
  - port: 8500
    name: http
  - port: 8600
    name: dns
  clusterIP: None
  selector:
    app: consul
---
apiVersion: v1
kind: Service
metadata:
  name: consul-ui
  labels:
    app: consul
spec:
  ports:
  - port: 8500
    targetPort: 8500
    protocol: TCP
    name: http
  selector:
    app: consul
  type: LoadBalancer
