apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"
        - name: MYSQL_DATABASE
          value: "mydatabase"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      - name: consul-agent
        image: hashicorp/consul:latest
        env:
        - name: CONSUL_LOCAL_CONFIG
          value: |
            {
              "datacenter": "dc1",
              "server": false,
              "services": [
                {
                  "name": "mysql",
                  "port": 3306,
                  "checks": [
                    {
                      "id": "mysql-check",
                      "name": "MySQL TCP on port 3306",
                      "tcp": "localhost:3306",
                      "interval": "10s",
                      "timeout": "1s"
                    }
                  ]
                }
              ]
            }
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        args:
        - "agent"
        - "-bind=$(POD_IP)"
        - "-retry-join=consul-0.consul"
        - "-retry-join=consul-1.consul"
        - "-retry-join=consul-2.consul"
        volumeMounts:
        - name: consul-data
          mountPath: /consul/data
        - name: consul-config
          mountPath: /consul/config
      volumes:
      - name: mysql-data
        emptyDir: {}
      - name: consul-data
        emptyDir: {}
      - name: consul-config
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    name: mysql
  selector:
    app: mysql
  type: ClusterIP
