apiVersion: v1
kind: ConfigMap
metadata:
  name: startup-script
data:
  startup.sh: |
    #!/bin/bash
    echo "Executing startup script..."

    # Install dnsmasq
    apt-get update -y
    apt-get install dnsmasq dnsutils ldnsutils -y
    apt install iputils-ping -y
    apt install dnsutils -y
    apt install mysql-client -y
    
    # Configure dnsmasq
    echo "server=/consul/consul.default.svc.cluster.local#8600\nserver=10.96.0.10" > /etc/dnsmasq.d/10-consul

    # Start dnsmasq
    /etc/init.d/dnsmasq start

    # Configure resolve.conf
    awk 'NR > 1' /etc/resolv.conf > /tmp/temp 
    echo "nameserver 127.0.0.1" | tee -a /tmp/temp
    cp /tmp/temp /etc/resolv.conf
    
    # Wait forever
    sleep infinity
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-client
  labels:
    app: ubuntu-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-client
  template:
    metadata:
      labels:
        app: ubuntu-client
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:24.04
        command: ["sh", "/startup.sh"]
        tty: true
        volumeMounts:
        - name: startup-script-volume
          mountPath: /startup.sh
          subPath: startup.sh  # Specify the file name in the ConfigMap
      volumes:
      - name: startup-script-volume
        configMap:
          name: startup-script
